### PR TITLE
docutils: rebuilt with python3 bindings; certifi: new release

### PR DESCRIPTION
**Pull request by blue-devil**

### CODE REVIEW

**Comment by paledega** [comment]
Thanks for pull request

**Comment by paledega** [comment]
@Zaryob @sulincix and me will merge this.

**Comment by sulincix** [comment]
👍

**Comment by Zaryob** [comment]
[AutoPackSRV] > Taking changes inside the compile query.
[AutoPackSRV] > Scheduled to be compiled and tested

**Comment by Zaryob** [comment]
[AutoPackSRV] > Taking compile query. Changes: {docutils, inary, python3-certifi, spotify-tui, and 35 more}

**Comment by Zaryob** [comment]
[AutoPackSRV] > docutils compiled

**Comment by Zaryob** [comment]
[AutoPackSRV] > certifi compiled

**Pull request merged**
